### ISSUE TITLE
 REST package fails to find materials... 

### ISSUE THREAD

**Issue by tsiledak** [rest-for-physics/restG4#112]
Dear experts,

I would like to ask you whether you could help me to run REST.

In my ubuntu 23.04 laptop I have installed:

-> ROOT version: 6.29/01

-> Geant4 version: 11.1.1

I followed the instructions in the REST page and I installed it using:

~/rest-framework/build$ cmake -DREST_EVE=OFF  -DRESTLIB_AXION=OFF .. -DREST_ALL_LIBS=ON -DCMAKE_INSTALL_PREFIX=../install/master/

And then:

~/rest-framework/build$ make -j4 install

I am getting the following message afterwards:

  *****************************************************************************
  W E L C O M E   to  R E S T  
 
  Commit  : 7148a3e0 (2022-01-29 11:52:36 +0100)  
  Branch/Version : official/v2.3.10  
  Compilation date : 2023-07-11 13:20  
  Official release : Yes
  Clean state : No
 
  Installed at : /home/gt226504/rest-framework/install/master  
 
  REST-for-Physics site : rest-for-physics.github.io  
 
  Remember that REST is made by physicists for physicists,
  who are supposed to toil and suffer till they become experts.
  *****************************************************************************

Then, I would like to run an example (I am mostly interested in the

08.Alphas)...

Anyway, If I choose the:

~/rest-framework/install/master/examples/restG4/01.NLDBD

and type:

restG4 NLDBD.rml

I am getting:

Command line parameters configuration:
    - RML file: NLDBD.rml
    - Execution mode: serial
Reading generator file : /home/gt226504/rest-framework/install/master/data/generator/Xe136bb0n.dat
Total number of events : 20000
GDML: initializating variables
GDML: replacing expressions in GDML
GDML: replacing entitiy: geometry, file: myGeometryTemplate.gdml
GDML: replacing entitiy: materials, file: https://sultan.unizar.es/materials/materials.xml
-- Error : download failed! (https://sultan.unizar.es/materials/materials.xml)
-- Error : File does NOT exist in remotely?
GDML: Download failed!

It seems there is no access in https://sultan.unizar.es/materials/materials.xml

I tried to edit the mySetupTemplate.gdml found in the geometry subdir by changing the path in a locally placed materials.xml file but in vain...

Could you please have a look and let me know what is wrong?

Thanks a lot in advance

Best regards

Georgios

**Comment by tsiledak** [comment]
Hi Javier,

Thanks so much for your help... I am afraid that more issues come out with the latest release...

I did the following:
rm -rf rest-framework
git clone https://github.com/rest-for-physics/framework rest-framework
cd rest-framework
git checkout tags/v2.4.0
python3 pull-submodules.py --clean
git checkout -b official
mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=../install -DREST_ALL_LIBS=ON -DREST_G4=ON ..

and got:

CMake Error at /home/gt226504/install/root_build/ROOTConfig.cmake:167 (message):
  ROOT component Eve not found

Then, 

~/rest-framework/build$ cmake -DREST_EVE=OFF .. -DCMAKE_INSTALL_PREFIX=../install -DREST_ALL_LIBS=ON -DREST_G4=ON ..

that works resulting in:

-- ########## Latest release info #############
-- Release version : 2.4.0
-- Release name : Alexander Friedmann
-- Release date : Fri 16 Jun
-- ########## Latest release info #############

-- Configuring done
-- Generating done
-- Build files have been written to: /home/gt226504/rest-framework/build

BUT with ~/rest-framework/build$ make -j install

there is the following error:
[  7%] generating: /home/gt226504/rest-framework/build/rootdict/CINT_TRestTask.cxx with /home/gt226504/rest-framework/source/framework/core/inc/TRestTask.h;/home/gt226504/rest-framework/build/rootdict/TRestTask_Linkdef.h
In file included from input_line_9:3:
/home/gt226504/rest-framework/source/framework/core/inc/TRestEveEventViewer.h:18:10: fatal error: 'TEveArrow.h' file not found
#include <TEveArrow.h>


I have 

-> ROOT version: 6.29/01

-> Geant4 version: 11.1.1

Any idea what is wrong?

Thanks a lot in advance

Georgios

**Comment by jgalan** [comment]
It seems to me a problem with the compilation system, probably `REST_EVE=OFF` is not properly identified in the second round.

We didn't find this issue because our ROOT compilation is linking to `Eve` libraries. I recommend to compile using ROOT-Eve libraries since the drawing of Geant4 events is done using them.


We will need to look deeper into the compilation system problem but in the meanwhile you could try the following.

Solution 1. Remove, the build directory and try from scratch.

```
cd rest-framework
rm -rf build
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=../install -DREST_ALL_LIBS=ON -DREST_G4=ON -DREST_EVE=OFF ..
make -j install
```

Solution 2: Compile ROOT with Eve libraries enabled.



Please, let me know how it goes.

**Comment by tsiledak** [comment]
Hi Javier,

I tried the first option but it did not work :-( since I got the following error after " make -j install"...
I will try the second one and let you know.
Thanks a lot

[  7%] generating: /home/gt226504/rest-framework/build/rootdict/CINT_TRestSpiderMask.cxx with /home/gt226504/rest-framework/source/framework/masks/inc/TRestSpiderMask.h;/home/gt226504/rest-framework/build/rootdict/TRestSpiderMask_Linkdef.h
In file included from input_line_9:3:
/home/gt226504/rest-framework/source/framework/core/inc/TRestEveEventViewer.h:18:10: fatal error: 'TEveArrow.h' file not found
#include <TEveArrow.h>
         ^~~~~~~~~~~~~
Error: /home/gt226504/install/root_build/bin/rootcint: compilation failure (/home/gt226504/rest-framework/build/rootdict/CINT_TRestEveEventViewer7364de2663_dictUmbrella.h)
make[2]: *** [source/framework/CMakeFiles/RestFramework.dir/build.make:110: rootdict/CINT_TRestEveEventViewer.cxx] Error 1
make[2]: *** Waiting for unfinished jobs....
Warning: Unused class rule: std::vector<Panel_Info>
Warning: Unused class rule: Panel_Info
Warning: Unused class rule: std::vector<Plot_Info_Set>
Warning: Unused class rule: Plot_Info_Set
Warning: Unused class rule: std::vector<Graph_Info_Set>
Warning: Unused class rule: Graph_Info_Set
Warning: Unused class rule: std::vector<PanelInfo>
Warning: Unused class rule: PanelInfo
Warning: Unused class rule: std::vector<PlotInfoSet>
Warning: Unused class rule: PlotInfoSet
Warning: Unused class rule: std::vector<HistoInfoSet>
Warning: Unused class rule: HistoInfoSet
Warning: Unused class rule: std::map<std::string, RelevantQuantity>
Warning: Unused class rule: RelevantQuantity
Warning: Unused class rule: std::map<std::string, RelevantQuantity>
Warning: Unused class rule: RelevantQuantity
Warning: Unused class rule: std::vector<PanelInfo>
Warning: Unused class rule: PanelInfo
Warning: Unused class rule: std::vector<PlotInfo>
Warning: Unused class rule: PlotInfo
Warning: Unused class rule: std::vector<HistoInfo>
Warning: Unused class rule: HistoInfo
make[1]: *** [CMakeFiles/Makefile2:376: source/framework/CMakeFiles/RestFramework.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by tsiledak** [comment]
Hi Javier, sorry for bothering again...

I finally reinstalled from ~/rest-framework/scripts/installation the root, geant4, executing the corresponding  sh files.
I recompile rest and it seems ok now.
 *****************************************************************************
  W E L C O M E   to  R E S T  
  
  Commit  : 075f65d7 (2023-06-16 15:23:05 +0200)  
  Branch/Version : official/v2.4.0  
  Compilation date : 2023-07-12 12:09  
  
  Latest release: : v2.4.0 - Alexander Friedmann - Fri 16 Jun  
  
  Official release : Yes 
  Clean state : Yes 
  
  Installed at : /home/gt226504/rest-framework/install  
  
  REST-for-Physics site : rest-for-physics.github.io  
  
  Remember that REST is made by physicists for physicists, 
  who are supposed to toil and suffer till they become experts. 
  *****************************************************************************

The example ~/rest-framework/install/examples/restG4/01.NLDBD runs BUT when I open the root file I am getting:
ROOT 6.28/02 

root [1] Warning in <TClass::Init>: no dictionary for class TRestRun is available
Warning in <TClass::Init>: no dictionary for class TRestMetadata is available
Warning in <TClass::Init>: no dictionary for class TRestAnalysisTree is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4Metadata is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4GeometryInfo is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4PhysicsInfo is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4PrimaryGeneratorInfo is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4ParticleSource is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4Particle is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4PhysicsLists is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4Event is available
Warning in <TClass::Init>: no dictionary for class TRestEvent is available
Error in <TStreamerInfo::Build>: The class "pair<string,map<string,map<string,double> > >" is interpreted and for its data member "second" we do not have a dictionary for the collection "map<string,map<string,double> >". Because of this, we will not be able to read or write this data member.
Warning in <TClass::Init>: no dictionary for class TRestGeant4Track is available
Warning in <TClass::Init>: no dictionary for class TRestGeant4Hits is available
Warning in <TClass::Init>: no dictionary for class TRestHits is available
(TFile *) 0x5557a6135340

I tried to execute the  08.Alphas example but with the same errors in root, even if the run takes place...

Best regards

Georgios

**Comment by tsiledak** [comment]
By the way, I tried the example: https://github.com/rest-for-physics/restG4/tree/master/examples/14.DetectorResponse
and was able to reproduce exactly the same picture result for pure xenon.
But in the the case of Alphas what I get is:

~/rest-framework/install/examples/restG4/08.Alphas-1$ restRoot plots.root
= Loading libraries ...
 - /home/gt226504/rest-framework/install/lib/libRestFramework.so
 - /home/gt226504/rest-framework/install/lib/libRestAxion.so
 - /home/gt226504/rest-framework/install/lib/libRestDetector.so
 - /home/gt226504/rest-framework/install/lib/libRestTrack.so
 - /home/gt226504/rest-framework/install/lib/libRestWimp.so
 - /home/gt226504/rest-framework/install/lib/libRestGeant4.so
 - /home/gt226504/rest-framework/install/lib/libRestLegacy.so
 - /home/gt226504/rest-framework/install/lib/libRestConnectors.so
 - /home/gt226504/rest-framework/install/lib/libRestRaw.so


Attaching file plots.root as run0...
Error in <TFile::GetObjectChecked>: The provided key name is invalid.
-- Warning : TRestRun::GetMetadataClass() : The object to import is not inherited from TRestMetadata
-- Warning : TRestRun object not found in file! The input file is problematic!
Attaching ana_tree0...
Attaching ev_tree0...

Attaching metadata structures...
root [0] new TBrowser
(TBrowser *) 0x55fef4b1aef0
root [1]

**Comment by jgalan** [comment]
Hi Georgios, sorry for the late reply. In principle the `plots.root` is a pure root file. You may check inside to see what it contains using simply the `root` command, `restRoot` is not necessary here:

```
root plots.root
.ls
```

**Comment by jgalan** [comment]
In my case I get an empty window named `c1` and a window with the 3D OpenGL view.

![Screenshot 2023-07-17 at 10 54 56](https://github.com/rest-for-physics/restG4/assets/12447509/5e184260-2b90-4b66-884a-89ec7bd03461)

Perhaps it is because Eve or OpenGL libraries are missing on your ROOT installation?

If you don't use the "ogl" option then you will get something drawn on the `c1` canvas.


![Screenshot 2023-07-17 at 10 56 59](https://github.com/rest-for-physics/restG4/assets/12447509/a33b483d-ca38-4db9-88f8-2a82c8ba8c95)

My guess is that openGL libraries were not found by your ROOT compilation.

**Comment by tsiledak** [comment]
Hi Javier,

Thanks so much for your feedback. I have included the openGL lib onto root and it works!
What is left is the broken root file as you could see in the attached pict.
When I open the Run_5MeV_1um.root, the energy deposition spectrum is found as it can be shown in the 2nd pict BUT not in the 
plots.root

Best regards
![image](https://github.com/rest-for-physics/restG4/assets/139242604/cd29d225-4c8a-40c0-b2db-9346f0af1a3c)

![image](https://github.com/rest-for-physics/restG4/assets/139242604/2f9f08a4-b18a-40e6-b1bd-9e84e05db405)

**Comment by jgalan** [comment]
Indeed, the `plots.root` file is not a REST generated file. You should open it with a plain `root` command.

```
root plots.root
```

Only REST processed files, containing event data, will contain a `TRestRun` and will be properly open using `restRoot`. Also other `REST` objects can be open, such as `TRestDataSet`, etc.
