### ISSUE TITLE
Can not find config file in 01.alphaTrack example 

### ISSUE THREAD

**Issue by tsiledak** [rest-for-physics/restG4#122]
Dear  experts,

I am trying to execute the example: 01.alphaTrack
I am following the procedure explained in README.md
But when I execute: 
restManager --c processing --f data/Run_5MeV_1um.root

gt226504@dphnpct97:~/myWorkDir/01.alphaTrack$       **restManager --c processing --f data/Run_5MeV_1um.root**
Starting pid: 25273
                      
           [==                                  Launching TRestManager...                                   ==]           
                      
           [==                                    Creating TRestManager                                     ==]           
           [==                                            path:                                             ==]           
**-- Error : Filename: 
-- Error : Config File does not exist. Right path/filename?**
Press a KEY to continue ...

           [==                                            Done!                                             ==]      

I am getting those errors...
What might be wrong? The file data/Run_5MeV_1um.root was created as stated in the README file...

Thanks a lot in advance

Best regards

Georgios

**Comment by lobis** [comment]
Hello @tsiledak ,

Looks like you are not correctly selecting the configuration file. What comes after the `--c` options should be the name of a configuration file (rml file). `processing` may not be how the file is named, perhaps it's named `processing.rml`?

**Comment by tsiledak** [comment]
Thanks so much!
I actually had a look at the 01.alphaTrack directory where the README file requires:
 restManager --c processing --f data/Run_5MeV_1um.root

But when I execute the same line named processing.rml, it seems that it works!

**Comment by jgalan** [comment]
Thanks for the feedback Giorgos, I just fixed the typo in our README.

Please, approve https://github.com/rest-for-physics/framework/pull/491

**Comment by jgalan** [comment]
Please @tsiledak accept the invitation as a member at rest-for-physics so that I can ask you to review the PR mentioned in this issue
