### ISSUE TITLE
Hadronics physics list mismatch

### ISSUE THREAD

**Issue by lobis** [rest-for-physics/restG4#2]
There is an error in the physics lists such that when selecting `G4HadronPhysicsQGSP_BIC_HP` as a physics list `G4HadronElasticPhysicsHP` is being loaded, and vice versa. This is easy to correct but could have potentially lead to inaccurate physics results.

**Comment by jgalan** [comment]
Ok, I think this is the time to tag a first version of `restG4` and update the reference at the main framework.

**Comment by jgalan** [comment]
Please @lobis try to follow the commit message recommendations at https://github.com/rest-for-physics/framework/blob/master/CONTRIBUTING.md

It should at least appear the name of the main modified file.

**Comment by jgalan** [comment]
I have created a first v1.0 release to start with a reference point. 

https://github.com/rest-for-physics/restG4/releases/tag/v1.0

And any info you think it is relevant there. I connected v1.0 release to the main framework repository.

https://github.com/rest-for-physics/framework/commits/development
