### ISSUE TITLE
unmatched time unit of hit points

### ISSUE THREAD

**Issue by nkx111** [rest-for-physics/restG4#6]
I see the time variable `hit_global_time` is in unit "second" from the code. 

https://github.com/rest-for-physics/restG4/blob/db031b409972be685610447e42739f4835f95642/src/SteppingAction.cc#L133

However in TRestHits the time unit is "micro second":

https://github.com/rest-for-physics/framework/blob/master/source/framework/core/inc/TRestHits.h#L52

**Comment by lobis** [comment]
Fixed at some point in the past, we should've closed this issue then.
