### ISSUE TITLE
Cannot distinguish two decays within ~100s

### ISSUE THREAD

**Issue by nkx111** [rest-for-physics/restG4#7]
We use a parameter `subEventTimeDelay` to make restG4 split the event into multiple sub-events. The logic is that, if the timediff between a track and its previous track is larger than `subEventTimeDelay`, it will store the track to another event.

The problem is that, the precision of `double` value is not enough when comparing two timestamps, when the decay time is very long. For example in U238 decay, the absolute timestamp is in the order of 1e17s. Usually the `double` type provides 15 digits of precision. Therefore, if the two radioactive decay is with in 100s, it cannot distinguish them. This makes the option `subEventTimeDelay` unusable. It makes hard to simulate bi-po coincidences with REST.

The solution could be to use relative timestamp instead of absolute timestamp. The following shows two same events but with different sub-event splitting logic.

### old logic

<details>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\bur_n\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\bur_n\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

tck id | sub ev id | particle | track global time (s) | track local time (s)
-- | -- | -- | -- | --
0 | 0 | U238 | 0 | 4.2447371604347200E+17
1 | 1 | alpha | 4.244737160434721e+17 | 2.2473104810782000E-10
2 | 1 | Th234[49.550] | 4.244737160434721e+17 | 2.3627502164090700E-13
3 | 1 | e- | 4.244737160434721e+17 | 1.9722337146653700E-12
4 | 1 | e- | 4.244737160434721e+17 | 2.0158855303878700E-13
5 | 1 | e- | 4.244737160434721e+17 | 6.3978247081795900E-14
6 | 1 | e- | 4.244737160434721e+17 | 8.6970941963494800E-14
7 | 1 | Th234 | 4.244737160434721e+17 | 4.3817914726905000E+05
8 | 2 | e- | 4.244737160439102e+17 | 4.7173360734851100E-12
9 | 2 | anti_nu_e | 4.244737160439102e+17 | 4.6311528830542500E-08
10 | 2 | Pa234[73.920] | 4.244737160439102e+17 | 6.5184451800137100E+01
11 | 3 | e- | 4.244737160439103e+17 | 6.9397118363730500E-10
12 | 3 | gamma | 4.244737160439103e+17 | 1.6419757286590300E-10
13 | 3 | gamma | 4.244737160439103e+17 | 1.8979029004466100E-10
14 | 3 | gamma | 4.244737160439103e+17 | 2.6449500816105300E-12
15 | 3 | gamma | 4.244737160439103e+17 | 3.4405715685805800E-11
16 | 3 | anti_nu_e | 4.244737160439103e+17 | 3.7507717461886100E-08
17 | 3 | U234 | 4.244737160439103e+17 | 1.6439569318608800E+13
23 | 3 | e- | 4.244737160439103e+17 | 1.5638311656135000E-12
24 | 3 | e- | 4.244737160439103e+17 | 8.4039064242145300E-14
25 | 3 | e- | 4.244737160439103e+17 | 1.3629692033232800E-12
26 | 3 | e- | 4.244737160439103e+17 | 7.4942411316369600E-12
18 | 4 | alpha | 4.244901556132289e+17 | 2.5090336716911800E-10
19 | 4 | Th230[53.227] | 4.244901556132289e+17 | 5.7028576098364300E-11
20 | 4 | e- | 4.244901556132289e+17 | 4.7376876887927900E-12
21 | 4 | e- | 4.244901556132289e+17 | 1.9141363857818900E-14
22 | 4 | e- | 4.244901556132289e+17 | 2.9515706608150600E-14
27 | 4 | Th230 | 4.244901556132289e+17 | 1.8564924762093900E+12
28 | 5 | alpha | 4.244920121057051e+17 | 2.3467227344421100E-10
29 | 5 | Ra226 | 4.244920121057051e+17 | 1.3912987555459200E+11
30 | 6 | alpha | 4.244921512355807e+17 | 2.5642702716609500E-10
31 | 6 | Rn222 | 4.244921512355807e+17 | 2.2426588595833600E+05
32 | 7 | alpha | 4.244921512358049e+17 | 2.7344977794615200E-10
33 | 7 | Po218 | 4.244921512358049e+17 | 1.8764543106643800E+03
34 | 8 | alpha | 4.244921512358067e+17 | 2.7488275167912500E-10
35 | 8 | Pb214 | 4.244921512358067e+17 | 2.4323111681253100E+03
36 | 9 | e- | 4.244921512358092e+17 | 2.9889840996938300E-11
37 | 9 | anti_nu_e | 4.244921512358092e+17 | 3.1422397542024500E-08
38 | 9 | Bi214 | 4.244921512358092e+17 | 3.1592888045601200E+03
39 | 10 | e- | 4.244921512358123e+17 | 1.2945295448472700E-09
40 | 10 | gamma | 4.244921512358123e+17 | 6.7925681489312600E-13
41 | 10 | gamma | 4.244921512358123e+17 | 1.3202138702722000E-10
42 | 10 | gamma | 4.244921512358123e+17 | 2.2574946629699100E-12
43 | 10 | gamma | 4.244921512358123e+17 | 8.5524236404013700E-14
44 | 10 | gamma | 4.244921512358123e+17 | 2.3680341561571000E-12
45 | 10 | anti_nu_e | 4.244921512358123e+17 | 3.7580287941371600E-08
46 | 10 | Po214 | 4.244921512358123e+17 | 1.5609894563087000E-04
47 | 10 | alpha | 4.244921512358123e+17 | 3.5695269307116900E-10
48 | 10 | Pb210 | 4.244921512358123e+17 | 4.2230631782614600E+07
50 | 10 | e- | 4.244921512358123e+17 | 7.9872453786296100E-14
51 | 10 | e- | 4.244921512358123e+17 | 7.1400608857472500E-14
52 | 10 | e- | 4.244921512358123e+17 | 7.1400608857472500E-14
53 | 10 | e- | 4.244921512358123e+17 | 2.2029980968217200E-12
54 | 10 | e- | 4.244921512358123e+17 | 1.8998857039026100E-13
49 | 11 | e- | 4.24492151278043e+17 | 2.5186675765200400E-13
55 | 11 | anti_nu_e | 4.24492151278043e+17 | 3.4017814048876600E-08
56 | 11 | Bi210[46.539] | 4.24492151278043e+17 | 9.4087768643599600E-11
57 | 11 | e- | 4.24492151278043e+17 | 1.8730731522390700E-12
58 | 11 | e- | 4.24492151278043e+17 | 4.7498045035780900E-14
59 | 11 | e- | 4.24492151278043e+17 | 1.3402635939838500E-13
60 | 11 | e- | 4.24492151278043e+17 | 1.5587936014848800E-14
61 | 11 | e- | 4.24492151278043e+17 | 2.5742686384814000E-14
62 | 11 | e- | 4.24492151278043e+17 | 4.3654916415301700E-14
63 | 11 | e- | 4.24492151278043e+17 | 1.5865393103639900E-14
64 | 11 | e- | 4.24492151278043e+17 | 1.5214750429908200E-14
65 | 11 | e- | 4.24492151278043e+17 | 1.1035552453717500E-13
66 | 11 | Bi210 | 4.24492151278043e+17 | 9.4651206970438200E+04
67 | 12 | e- | 4.244921512781376e+17 | 3.3278013313713000E-10
68 | 12 | anti_nu_e | 4.244921512781376e+17 | 4.0932319128091100E-08
69 | 12 | Po210 | 4.244921512781376e+17 | 2.5297501695599000E+07
70 | 13 | alpha | 4.244921513034351e+17 | 2.5680834694025800E-10
71 | 13 | Pb206 | 4.244921513034351e+17 | 8.4254236934789200E-11

</body>

</html>

</details>

### use relative time stamp

<details>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\bur_n\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\bur_n\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

tck id | parent id | sub ev id | particle | track global time (s) | track local time (s)
-- | -- | -- | -- | -- | --
1 | 0 | 0 | U238 | 0 | 4.2447371604347200E+17
2 | 1 | 1 | Th234[49.550] | 4.244737160434721e+17 | 2.3627502164090700E-13
3 | 1 | 1 | alpha | 4.244737160434721e+17 | 2.2473104810782000E-10
4 | 2 | 1 | Th234 | 4.244737160434721e+17 | 4.3817914726905000E+05
5 | 2 | 1 | e- | 4.244737160434721e+17 | 8.6970941963494800E-14
6 | 2 | 1 | e- | 4.244737160434721e+17 | 6.3978247081795900E-14
7 | 2 | 1 | e- | 4.244737160434721e+17 | 2.0158855303878700E-13
8 | 2 | 1 | e- | 4.244737160434721e+17 | 1.9722337146653700E-12
9 | 4 | 2 | Pa234[73.920] | 4.244737160439102e+17 | 6.5184451800137100E+01
10 | 4 | 2 | anti_nu_e | 4.244737160439102e+17 | 4.6311528830542500E-08
11 | 4 | 2 | e- | 4.244737160439102e+17 | 4.7173360734851100E-12
12 | 9 | 3 | U234 | 4.244737160439103e+17 | 1.6439569318608800E+13
13 | 9 | 3 | anti_nu_e | 4.244737160439103e+17 | 3.7507717461886100E-08
14 | 9 | 3 | e- | 4.244737160439103e+17 | 6.9397118363730500E-10
15 | 14 | 3 | gamma | 4.244737160439103e+17 | 3.4405715685805800E-11
16 | 14 | 3 | gamma | 4.244737160439103e+17 | 2.6449500816105300E-12
17 | 14 | 3 | gamma | 4.244737160439103e+17 | 1.6419757286590300E-10
18 | 17 | 3 | e- | 4.244737160439103e+17 | 7.4942411316369600E-12
19 | 17 | 3 | gamma | 4.244737160439103e+17 | 1.8979029004466100E-10
20 | 19 | 3 | e- | 4.244737160439103e+17 | 1.3629692033232800E-12
21 | 16 | 3 | e- | 4.244737160439103e+17 | 8.4039064242145300E-14
22 | 15 | 3 | e- | 4.244737160439103e+17 | 1.5638311656135000E-12
23 | 12 | 4 | Th230[53.227] | 4.244901556132289e+17 | 5.7028576098364300E-11
24 | 12 | 4 | alpha | 4.244901556132289e+17 | 2.5090336716911800E-10
25 | 23 | 4 | Th230 | 4.244901556132289e+17 | 1.8564924762093900E+12
26 | 23 | 4 | e- | 4.244901556132289e+17 | 2.9515706608150600E-14
27 | 23 | 4 | e- | 4.244901556132289e+17 | 1.9141363857818900E-14
28 | 23 | 4 | e- | 4.244901556132289e+17 | 4.7376876887927900E-12
29 | 25 | 5 | Ra226 | 4.244920121057051e+17 | 1.3912987555459200E+11
30 | 25 | 5 | alpha | 4.244920121057051e+17 | 2.3467227344421100E-10
31 | 29 | 6 | Rn222 | 4.244921512355807e+17 | 2.2426588595833600E+05
32 | 29 | 6 | alpha | 4.244921512355807e+17 | 2.5642702716609500E-10
33 | 31 | 7 | Po218 | 4.244921512358049e+17 | 1.8764543106643800E+03
34 | 31 | 7 | alpha | 4.244921512358049e+17 | 2.7344977794615200E-10
35 | 33 | 8 | Pb214 | 4.244921512358067e+17 | 2.4323111681253100E+03
36 | 33 | 8 | alpha | 4.244921512358067e+17 | 2.7488275167912500E-10
37 | 35 | 9 | Bi214 | 4.244921512358092e+17 | 3.1592888045601200E+03
38 | 35 | 9 | anti_nu_e | 4.244921512358092e+17 | 3.1422397542024500E-08
39 | 35 | 9 | e- | 4.244921512358092e+17 | 2.9889840996938300E-11
40 | 37 | 10 | Po214 | 4.244921512358123e+17 | 1.5609894563087000E-04
41 | 37 | 10 | anti_nu_e | 4.244921512358123e+17 | 3.7580287941371600E-08
42 | 37 | 10 | e- | 4.244921512358123e+17 | 1.2945295448472700E-09
43 | 42 | 10 | gamma | 4.244921512358123e+17 | 2.3680341561571000E-12
44 | 42 | 10 | gamma | 4.244921512358123e+17 | 8.5524236404013700E-14
45 | 42 | 10 | gamma | 4.244921512358123e+17 | 2.2574946629699100E-12
46 | 42 | 10 | gamma | 4.244921512358123e+17 | 1.3202138702722000E-10
47 | 42 | 10 | gamma | 4.244921512358123e+17 | 6.7925681489312600E-13
48 | 47 | 10 | e- | 4.244921512358123e+17 | 1.8998857039026100E-13
49 | 46 | 10 | e- | 4.244921512358123e+17 | 2.2029980968217200E-12
50 | 45 | 10 | e- | 4.244921512358123e+17 | 7.1400608857472500E-14
51 | 44 | 10 | e- | 4.244921512358123e+17 | 7.1400608857472500E-14
52 | 43 | 10 | e- | 4.244921512358123e+17 | 7.9872453786296100E-14
53 | 40 | 11 | Pb210 | 4.244921512358123e+17 | 4.2230631782614600E+07
54 | 40 | 11 | alpha | 4.244921512358123e+17 | 3.5695269307116900E-10
55 | 53 | 12 | Bi210[46.539] | 4.24492151278043e+17 | 9.4087768643599600E-11
56 | 53 | 12 | anti_nu_e | 4.24492151278043e+17 | 3.4017814048876600E-08
57 | 53 | 12 | e- | 4.24492151278043e+17 | 2.5186675765200400E-13
58 | 55 | 12 | Bi210 | 4.24492151278043e+17 | 9.4651206970438200E+04
59 | 55 | 12 | e- | 4.24492151278043e+17 | 1.1035552453717500E-13
60 | 55 | 12 | e- | 4.24492151278043e+17 | 1.5214750429908200E-14
61 | 55 | 12 | e- | 4.24492151278043e+17 | 1.5865393103639900E-14
62 | 55 | 12 | e- | 4.24492151278043e+17 | 4.3654916415301700E-14
63 | 55 | 12 | e- | 4.24492151278043e+17 | 2.5742686384814000E-14
64 | 55 | 12 | e- | 4.24492151278043e+17 | 1.5587936014848800E-14
65 | 55 | 12 | e- | 4.24492151278043e+17 | 1.3402635939838500E-13
66 | 55 | 12 | e- | 4.24492151278043e+17 | 4.7498045035780900E-14
67 | 55 | 12 | e- | 4.24492151278043e+17 | 1.8730731522390700E-12
68 | 58 | 13 | Po210 | 4.244921512781376e+17 | 2.5297501695599000E+07
69 | 58 | 13 | anti_nu_e | 4.244921512781376e+17 | 4.0932319128091100E-08
70 | 58 | 13 | e- | 4.244921512781376e+17 | 3.3278013313713000E-10
71 | 68 | 14 | Pb206 | 4.244921513034351e+17 | 8.4254236934789200E-11
72 | 68 | 14 | alpha | 4.244921513034351e+17 | 2.5680834694025800E-10

</body>

</html>
</details>

**Comment by jgalan** [comment]
Yes, this was a known problem the time we launched restG4 simulations for PandaX-III CDR. The problem was "solved" by starting the 238U decay chain at 234Th, and launching 238U in singleDecay mode. In any case, 238U was not contributing to NLDBD.

 I agree relative timestamp would be a definite solution.
